BEGIN;
TRUNCATE "web_projects", "auth_group_permissions", "django_session", "django_content_type", "django_admin_log", "web_tasks", "web_comments", "web_employees", "authtoken_token", "web_photos", "web_clients", "web_user_user_permissions", "auth_permission", "web_likes", "web_plans", "web_geographical", "web_allowpersons", "web_commentsofweb", "web_user", "web_todo", "auth_group", "web_user_groups", "web_purchases", "web_gallery";
SELECT setval(pg_get_serial_sequence('"django_admin_log"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"auth_permission"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"auth_group"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"auth_group_permissions"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"django_content_type"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"web_user"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"web_user_groups"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"web_user_user_permissions"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"web_employees"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"web_purchases"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"web_clients"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"web_commentsofweb"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"web_geographical"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"web_projects"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"web_plans"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"web_allowpersons"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"web_tasks"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"web_todo"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"web_gallery"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"web_photos"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"web_comments"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"web_likes"','id'), 1, false);
COMMIT;
