# Generated by Django 2.1.4 on 2019-02-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('name', models.TextField()),
                ('personnelـid', models.BigIntegerField(max_length=16, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=32)),
                ('profile_pic', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('for_what', models.TextField()),
                ('date', models.TextField()),
            ],
        ),
    ]
