# Generated by Django 2.2.2 on 2019-06-16 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='gallery_name',
            new_name='name',
        ),
    ]
