# Generated by Django 2.1.7 on 2019-02-18 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='buyer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='web.Employees'),
            preserve_default=False,
        ),
    ]
