# Generated by Django 2.1.4 on 2019-02-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_purchases_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='post',
            field=models.TextField(default='متخصص برق'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employees',
            name='personnelـid',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
