# Generated by Django 2.2.2 on 2019-06-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190616_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchases',
            old_name='for_what',
            new_name='info',
        ),
        migrations.AddField(
            model_name='purchases',
            name='name',
            field=models.TextField(default='خرید'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchases',
            name='via',
            field=models.TextField(default='پرداخت اینترنتی'),
            preserve_default=False,
        ),
    ]
