# Generated by Django 2.1.7 on 2019-03-15 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190313_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Employees'),
        ),
    ]
