# Generated by Django 2.1.7 on 2019-05-02 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20190315_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='client',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='web.Clients'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='done',
            field=models.BooleanField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='price',
            field=models.BigIntegerField(default='12000000'),
            preserve_default=False,
        ),
    ]
