# Generated by Django 2.2.2 on 2019-06-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20190616_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='image',
            field=models.ImageField(default='media/default-project.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='purchases',
            name='receipt',
            field=models.ImageField(default='media/default-receipt.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='clients',
            name='profile_pic',
            field=models.ImageField(default='media/default-user.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='employees',
            name='profile_pic',
            field=models.ImageField(default='media/default-user.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='plans',
            name='photo',
            field=models.ImageField(default='media/default-plan.png', upload_to=''),
        ),
    ]
