# Generated by Django 2.2.2 on 2019-06-19 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20190619_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='profile_pic',
            field=models.ImageField(default='default-user.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='employees',
            name='profile_pic',
            field=models.ImageField(default='default-user.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='plans',
            name='photo',
            field=models.ImageField(default='default-plan.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(default='default-project.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='receipt',
            field=models.ImageField(default='default-receipt.jpg', upload_to=''),
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('info', models.TextField()),
                ('file', models.FileField(upload_to='')),
                ('time', models.DateTimeField(auto_now=True)),
                ('subtitle', models.TextField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Employees')),
            ],
        ),
    ]
