# Generated by Django 2.2.2 on 2019-06-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20190619_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='file',
            field=models.FileField(default='default-file.pdf', upload_to=''),
        ),
    ]
