# Generated by Django 2.1.7 on 2019-05-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_projects_geographical'),
    ]

    operations = [
        migrations.AddField(
            model_name='geographical',
            name='location',
            field=models.TextField(default='کرمان - میدان آزادی - خیابان ج'),
            preserve_default=False,
        ),
    ]
