# Generated by Django 2.2.2 on 2019-06-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20190620_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
