# Generated by Django 2.2.2 on 2019-06-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_notifications_notiperson_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='default-user.jpg', upload_to=''),
        ),
    ]
