# Generated by Django 2.1.7 on 2019-05-25 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('done', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='details',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='done',
        ),
        migrations.AddField(
            model_name='todo',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Tasks'),
        ),
    ]
