# Generated by Django 2.2.2 on 2019-06-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='post',
            field=models.TextField(default='مدیر'),
            preserve_default=False,
        ),
    ]
