# Generated by Django 2.1.7 on 2019-06-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20190525_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='caption',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
