# Generated by Django 2.2.2 on 2019-06-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='notiperson',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
