# Generated by Django 2.2.2 on 2019-06-28 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_notiperson_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='of_user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
