# Generated by Django 2.2.2 on 2019-06-28 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_notifications_of_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='of_user',
            new_name='from_user',
        ),
    ]
