# Generated by Django 2.2.2 on 2019-07-06 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_auto_20190706_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Clients'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='employer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Employees'),
        ),
    ]
