# Generated by Django 2.2.2 on 2019-07-06 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_auto_20190707_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='peymankar',
            field=models.TextField(default='مهدی عربپور'),
            preserve_default=False,
        ),
    ]
