# Generated by Django 2.2.2 on 2019-07-07 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_projects_peymankar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='geographical',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Geographical'),
        ),
    ]
