# Generated by Django 2.2.2 on 2019-07-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_auto_20190707_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='name',
            field=models.TextField(default='اسم نقشه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plans',
            name='name',
            field=models.TextField(default='اسم نقشه'),
            preserve_default=False,
        ),
    ]
