# Generated by Django 2.2.2 on 2019-07-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_auto_20190707_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='text',
            field=models.TextField(default='یک متن ساده'),
            preserve_default=False,
        ),
    ]
