# Generated by Django 2.2.2 on 2019-07-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_workspace_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='data',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='subtitle',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
