# Generated by Django 2.2.2 on 2019-07-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_auto_20190707_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='data',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='plans',
            name='kind',
            field=models.TextField(default='یک نقشه جدید'),
        ),
        migrations.AlterField(
            model_name='plans',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
